'use client';

import Link from 'next/link';
import { motion } from 'framer-motion';
import { HiArrowLeft } from 'react-icons/hi';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

export default function TermsOfService() {
    return (
        <main className="bg-[var(--background)] min-h-screen">
            <Navbar />

            <div className="pt-24 md:pt-32">
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6 }}
                    className="legal-content"
                >
                    {/* Back Link */}
                    <Link
                        href="/"
                        className="inline-flex items-center gap-2 text-[var(--foreground-muted)] hover:text-[var(--color-primary)] transition-colors mb-8"
                    >
                        <HiArrowLeft className="w-5 h-5" />
                        Back to Home
                    </Link>

                    <h1 className="gradient-text">Terms of Service</h1>
                    <p className="text-[var(--foreground-subtle)] mb-8">
                        Last updated: January 13, 2025
                    </p>

                    <h2>1. Acceptance of Terms</h2>
                    <p>
                        By accessing or using DevGPT (&quot;the App&quot;), you agree to be bound by these
                        Terms of Service. If you do not agree to these terms, please do not use the App.
                    </p>

                    <h2>2. Description of Service</h2>
                    <p>
                        DevGPT is an AI-powered mobile application that provides coding assistance,
                        including code generation, debugging help, and programming explanations. The
                        service uses artificial intelligence to respond to user queries about programming.
                    </p>

                    <h2>3. User Accounts</h2>
                    <p>
                        To access certain features, you may need to create an account. You are responsible for:
                    </p>
                    <ul>
                        <li>Maintaining the confidentiality of your account credentials</li>
                        <li>All activities that occur under your account</li>
                        <li>Providing accurate and complete registration information</li>
                        <li>Notifying us immediately of any unauthorized use of your account</li>
                    </ul>

                    <h2>4. Acceptable Use</h2>
                    <p>You agree not to use DevGPT to:</p>
                    <ul>
                        <li>Generate malicious code or malware</li>
                        <li>Violate any applicable laws or regulations</li>
                        <li>Infringe on intellectual property rights</li>
                        <li>Attempt to reverse engineer or exploit the service</li>
                        <li>Transmit harmful or offensive content</li>
                        <li>Interfere with the operation of the service</li>
                    </ul>

                    <h2>5. AI-Generated Content</h2>
                    <p>
                        The code and responses generated by DevGPT are provided &quot;as is.&quot; While we strive
                        for accuracy, you acknowledge that:
                    </p>
                    <ul>
                        <li>AI responses may contain errors or inaccuracies</li>
                        <li>You are responsible for reviewing and testing any generated code</li>
                        <li>The service is not a substitute for professional advice</li>
                        <li>We do not guarantee the suitability of generated code for any purpose</li>
                    </ul>

                    <h2>6. Intellectual Property</h2>
                    <p>
                        The DevGPT application, including its design, features, and content, is owned by
                        us and protected by intellectual property laws. You may use the generated code
                        for your personal or commercial projects, subject to any applicable open-source licenses.
                    </p>

                    <h2>7. Limitation of Liability</h2>
                    <p>
                        To the maximum extent permitted by law, DevGPT and its creators shall not be
                        liable for any indirect, incidental, special, consequential, or punitive damages,
                        including loss of profits, data, or other intangible losses resulting from your
                        use of the service.
                    </p>

                    <h2>8. Modifications to Service</h2>
                    <p>
                        We reserve the right to modify, suspend, or discontinue the service at any time
                        without prior notice. We may also update these Terms of Service from time to time.
                    </p>

                    <h2>9. Termination</h2>
                    <p>
                        We may terminate or suspend your access to the service immediately, without prior
                        notice or liability, for any reason, including breach of these Terms of Service.
                    </p>

                    <h2>10. Governing Law</h2>
                    <p>
                        These Terms shall be governed by and construed in accordance with the laws of
                        the jurisdiction in which DevGPT operates, without regard to its conflict of law provisions.
                    </p>

                    <h2>11. Contact Information</h2>
                    <p>
                        For questions about these Terms of Service, please contact us at{' '}
                        <a href="mailto:legal@devgpt.app" className="text-[var(--color-primary)]">
                            legal@devgpt.app
                        </a>
                    </p>
                </motion.div>
            </div>

            <Footer />
        </main>
    );
}
